name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, mysql, zip
        coverage: none
        tools: composer:v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          git config --global --add safe.directory /var/www/Stray-Safe
      
          sudo chown -R www-data:www-data /var/www/Stray-Safe
          sudo find /var/www/Stray-Safe -type f -exec chmod 664 {} \;
          sudo find /var/www/Stray-Safe -type d -exec chmod 775 {} \;
          sudo chmod -R 775 /var/www/Stray-Safe/storage /var/www/Stray-Safe/bootstrap/cache
      
          cd /var/www/Stray-Safe
          git pull origin main
      
          composer install --no-interaction --prefer-dist --optimize-autoloader
      
          npm install
          npm run build
      
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
      
          sudo systemctl reload nginx