name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DO_HOST: ${{ secrets.DO_HOST }}
        USERNAME: ${{ secrets.DO_USERNAME }}
        PASSWORD: ${{secrets.DO_PASSWORD}}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        echo $SSH_PRIVATE_KEY >> secrets.txt
        echo $DO_HOST >> secrets.txt
        echo $USERNAME >> secrets.txt
        echo $PASSWORD >> secrets.txt
        echo $SSH_PORT >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2